/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Interfaz.Auditoria.VistaAuditoria;
import Interfaz.bono.*;
import Interfaz.Usuarios.VistaUsuarios;
import Interfaz.Bus.VistaBus;
import Interfaz.Revision.VistaRevision;
import Interfaz.Rutas.VistaRutas;
import java.awt.*;
import sc.pkgProject_Lenjuage_BD.Project_Lenjuage_BD;

public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
        home_page();
        StatusDB.setText(Project_Lenjuage_BD.EstadoDB);
        if (StatusDB.getText() == "Conectado") {
            StatusDB.setForeground(Color.green);
        } else {
            StatusDB.setForeground(Color.red);
        }
    }

    public void home_page() {
        BG_inicio Imagen_fondo = new BG_inicio();
        Imagen_fondo.setSize(959, 558);
        Imagen_fondo.setLocation(0, 0);
        Contenido.add(Imagen_fondo, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_pane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel()
        {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                int w = getWidth();
                int h = getHeight();
                Color colorInicial = Color.decode("#659999"); // Color inicial en formato HEX
                Color colorFinal = Color.decode("#F5AF19"); // Color final en formato HEX
                GradientPaint gradientPaint = new GradientPaint(0, 0, colorInicial, w, h, colorFinal);
                g2d.setPaint(gradientPaint);
                g2d.fillRect(0, 0, w, h);
            }
        }
        ;
        Gestion_pacientes = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Mantenimiento = new javax.swing.JButton();
        Buses = new javax.swing.JButton();
        Bonos = new javax.swing.JButton();
        Rutas = new javax.swing.JButton();
        Contenido = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jToolBar3 = new javax.swing.JToolBar();
        StatusDB1 = new javax.swing.JLabel();
        StatusDB = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Proyecto Grupo 1");
        setResizable(false);

        BG_pane.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Menu Principal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(204, 0, 51))); // NOI18N

        Gestion_pacientes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Gestion_pacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuario-64.png"))); // NOI18N
        Gestion_pacientes.setText("Usuarios");
        Gestion_pacientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Gestion_pacientes.setBorderPainted(false);
        Gestion_pacientes.setContentAreaFilled(false);
        Gestion_pacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gestion_pacientes.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Gestion_pacientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Gestion_pacientes.setOpaque(false);
        Gestion_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gestion_pacientesActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(153, 0, 0));
        Salir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.setBorder(null);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Salir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Mantenimiento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mantenimiento-64.png"))); // NOI18N
        Mantenimiento.setText("Revisión");
        Mantenimiento.setBorder(null);
        Mantenimiento.setContentAreaFilled(false);
        Mantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mantenimiento.setHideActionText(true);
        Mantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Mantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoActionPerformed(evt);
            }
        });

        Buses.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Buses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-autobús-64.png"))); // NOI18N
        Buses.setText("Buses");
        Buses.setBorder(null);
        Buses.setContentAreaFilled(false);
        Buses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buses.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Buses.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Buses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusesActionPerformed(evt);
            }
        });

        Bonos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Bonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-bonus-64.png"))); // NOI18N
        Bonos.setText("Bonos");
        Bonos.setBorder(null);
        Bonos.setContentAreaFilled(false);
        Bonos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bonos.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Bonos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Bonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BonosActionPerformed(evt);
            }
        });

        Rutas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Rutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-navigation-64.png"))); // NOI18N
        Rutas.setText("Rutas");
        Rutas.setBorder(null);
        Rutas.setContentAreaFilled(false);
        Rutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rutas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Rutas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Rutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mantenimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
            .addComponent(Buses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Rutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Bonos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Gestion_pacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Gestion_pacientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buses, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Rutas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bonos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(Salir)
                .addContainerGap())
        );

        Contenido.setBackground(new java.awt.Color(51, 51, 51));
        Contenido.setOpaque(false);

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 51));
        jButton1.setText("Ver Auditorias");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jSeparator1.setMaximumSize(new java.awt.Dimension(10, 50));
        jSeparator1.setMinimumSize(new java.awt.Dimension(10, 50));
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 50));
        jToolBar1.add(jSeparator1);

        jToolBar3.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar3.setRollover(true);

        StatusDB1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        StatusDB1.setForeground(new java.awt.Color(255, 255, 255));
        StatusDB1.setText("Estado de conexión Oracle:");
        jToolBar3.add(StatusDB1);

        StatusDB.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        StatusDB.setText("Estado");
        jToolBar3.add(StatusDB);

        javax.swing.GroupLayout BG_paneLayout = new javax.swing.GroupLayout(BG_pane);
        BG_pane.setLayout(BG_paneLayout);
        BG_paneLayout.setHorizontalGroup(
            BG_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BG_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BG_paneLayout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BG_paneLayout.setVerticalGroup(
            BG_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BG_paneLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BG_paneLayout.createSequentialGroup()
                        .addGroup(BG_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Lenguaje de Base de Datos");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Gestion_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestion_pacientesActionPerformed
        VistaUsuarios Usuario = new VistaUsuarios();
        Usuario.setSize(959, 558);//646, 689 916, 558
        Contenido.removeAll();
        Contenido.add(Usuario, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_Gestion_pacientesActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        PopupDisconnect desconectar = new PopupDisconnect(this, rootPaneCheckingEnabled);
        desconectar.setVisible(true);
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void BusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusesActionPerformed
        VistaBus Bus = new VistaBus();
        Bus.setSize(959, 558);//646, 689 916, 558
        Contenido.removeAll();
        Contenido.add(Bus, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_BusesActionPerformed

    private void BonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BonosActionPerformed
        VistaBono Bono = new VistaBono();
        Bono.setSize(959, 558);//646, 689
        Contenido.removeAll();
        Contenido.add(Bono, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_BonosActionPerformed

    private void MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoActionPerformed
 VistaRevision mantenimiento = new VistaRevision();
        mantenimiento.setSize(959, 558);//646, 689 916, 558
        Contenido.removeAll();
        Contenido.add(mantenimiento, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();  
    }//GEN-LAST:event_MantenimientoActionPerformed

    private void RutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutasActionPerformed
        VistaRutas Rutas = new VistaRutas();
        Rutas.setSize(959, 558);//646, 689 916, 558 (959, 558)
        Contenido.removeAll();
        Contenido.add(Rutas, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();                       
    }//GEN-LAST:event_RutasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       VistaAuditoria Auditoria = new VistaAuditoria();
        Auditoria.setSize(959, 558);//646, 689 916, 558 (959, 558)
        Contenido.removeAll();
        Contenido.add(Auditoria, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_pane;
    private javax.swing.JButton Bonos;
    private javax.swing.JButton Buses;
    public static javax.swing.JPanel Contenido;
    private javax.swing.JButton Gestion_pacientes;
    private javax.swing.JButton Mantenimiento;
    private javax.swing.JButton Rutas;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel StatusDB;
    private javax.swing.JLabel StatusDB1;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
