/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.bono;

import ConectionDB.ConectionDB;
import java.awt.Color;
import popups.Popups;
import java.sql.*;


/**
 * @author ROURY
 */
public class AgregarBono extends javax.swing.JFrame {

    public static String Crud_;
    public static boolean isEdit_;
    public static String textoBoton_;
    public static int ID_aEditar_;
    private VistaBono vistaBono;

    Popups popups = new Popups();

    public AgregarBono() {
        initComponents();
       

    }

    //esto es un set no quitar el la palabra set antes del nombre del metodo
    public void setVistaBono(VistaBono vistaBono) {
        this.vistaBono = vistaBono;
    }

    public void actualizarTabla() {
        if (vistaBono != null) {
            vistaBono.cargarDatos();
        }
    }
    
    public void setDatosEdicion(String nombre, String monto, String anios_ant) {
        Nombre_Bono.setText(nombre);
        Monto.setText(monto);
        anios_minimo.setText(anios_ant);
    }

   

  
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cerrar = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        warning = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Nombre_Bono = new javax.swing.JTextField();
        Monto = new javax.swing.JTextField();
        anios_minimo = new javax.swing.JTextField();
        Error_fecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), Crud_ + " de Bonos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Cerrar.setBackground(new java.awt.Color(153, 0, 0));
        Cerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setText("Cerrar");
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        Registrar.setBackground(new java.awt.Color(0, 102, 255));
        Registrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setText(textoBoton_);
        Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        warning.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("* Campos Obligatorios");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Por favor llene toda la información necesaria");

        jPanel2.setBackground(new java.awt.Color(162, 171, 205));

        Nombre_Bono.setBackground(new java.awt.Color(255, 255, 255));
        Nombre_Bono.setForeground(new java.awt.Color(0, 0, 0));
        Nombre_Bono.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Nombre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        Nombre_Bono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Nombre_Bono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_BonoActionPerformed(evt);
            }
        });

        Monto.setBackground(new java.awt.Color(255, 255, 255));
        Monto.setForeground(new java.awt.Color(0, 0, 0));
        Monto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Monto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        Monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoActionPerformed(evt);
            }
        });
        Monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MontoKeyTyped(evt);
            }
        });

        anios_minimo.setBackground(new java.awt.Color(255, 255, 255));
        anios_minimo.setForeground(new java.awt.Color(0, 0, 0));
        anios_minimo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Años", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        anios_minimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anios_minimoActionPerformed(evt);
            }
        });
        anios_minimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anios_minimoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(anios_minimo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre_Bono, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Nombre_Bono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(anios_minimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Error_fecha.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Error_fecha.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 151, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(warning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Error_fecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(170, 170, 170))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(249, 249, 249)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(Error_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar)
                    .addComponent(Registrar))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CerrarActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        if (isEdit_) {
           String nombre = Nombre_Bono.getText();
            String monto = Monto.getText();
            String anios_minimosText = anios_minimo.getText();
            

          
            Color colorError = new Color(255, 204, 204);

            if (monto.isEmpty() || nombre.isEmpty()|| anios_minimosText.isEmpty() ) {

                if (nombre.isEmpty()) {
                    Nombre_Bono.setBackground(colorError);
                } else {
                    Nombre_Bono.setBackground(Color.WHITE);
                }
                if (monto.isEmpty()) {
                    Monto.setBackground(colorError);
                } else {
                    Monto.setBackground(Color.WHITE);
                }
                 if (anios_minimosText.isEmpty()) {
                    anios_minimo.setBackground(colorError);
                } else {
                    anios_minimo.setBackground(Color.WHITE);
                }

                warning.setText("ATENCIÓN: Por favor, complete todos los campos.");
                return;
            } else {
                Connection conn = null;
                CallableStatement stmt = null;

                try {
                    ConectionDB conexionDB = new ConectionDB();
                    conn = conexionDB.getConnection();

                    stmt = conn.prepareCall("{Call Bonos.Procedure_Actualizar_Bonos(?, ?, ?,?)}");

                    
                    stmt.setInt(1, ID_aEditar_); //no es ncesario convertir, ojo si se copia este formulario para otro uso
                    stmt.setString(2, nombre);
                    double montoDouble = Double.parseDouble(monto);
                    stmt.setDouble(3, montoDouble);
                    
                    double aniosDouble = Double.parseDouble(anios_minimosText);
                    stmt.setDouble(4, aniosDouble);
                    
                    stmt.executeUpdate();

                    popups.pulgar_arriba("Bono actualizado exitosamente.");
                    actualizarTabla();
                    this.setVisible(false);
                } catch (SQLException e) {
                    e.printStackTrace();
                    warning.setText("Error al actualizar la Bono: " + e.getMessage());
                } finally {
                    try {
                        if (stmt != null) {
                            stmt.close();
                        }
                        if (conn != null) {
                            conn.close();
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
            }
        } else {
            String nombre = Nombre_Bono.getText();
            String monto = Monto.getText();
            String anios_minimosText = anios_minimo.getText();
            System.out.println(nombre + monto+ anios_minimosText);
            

          
            Color colorError = new Color(255, 204, 204);

             if (monto.isEmpty() || nombre.isEmpty()|| anios_minimosText.isEmpty() ) {

                if (nombre.isEmpty()) {
                    Nombre_Bono.setBackground(colorError);
                } else {
                    Nombre_Bono.setBackground(Color.WHITE);
                }
                if (monto.isEmpty()) {
                    Monto.setBackground(colorError);
                } else {
                    Monto.setBackground(Color.WHITE);
                }
                 if (anios_minimosText.isEmpty()) {
                    anios_minimo.setBackground(colorError);
                } else {
                    anios_minimo.setBackground(Color.WHITE);
                }
                 warning.setText("ATENCIÓN: Por favor, complete todos los campos.");
                return;
            } else {

            Connection conn = null;
            CallableStatement stmt = null;

            try {
                ConectionDB conexionDB = new ConectionDB();
                conn = conexionDB.getConnection();

                String sql = "{CALL Bonos.PROCEDURE_Crear_Bonos(?, ?, ?)}";
                stmt = conn.prepareCall(sql);

                double montoDouble = Double.parseDouble(monto);
                stmt.setDouble(1, montoDouble);
                
                stmt.setString(2, nombre);
                
               double aniosDouble = Double.parseDouble(anios_minimosText);
                    stmt.setDouble(3, aniosDouble);

                stmt.executeUpdate();
                popups.pulgar_arriba("Bono registrada exitosamente.");
                actualizarTabla();
                this.setVisible(false);
            } catch (SQLException e) {
                e.printStackTrace();
                popups.error("Error al registrar el Bono.");
            } finally {
                try {
                    if (stmt != null) {
                        stmt.close();
                    }
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
        }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void MontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontoKeyTyped
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <= 57;
        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_MontoKeyTyped

    private void anios_minimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anios_minimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anios_minimoActionPerformed

    private void anios_minimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anios_minimoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_anios_minimoKeyTyped

    private void Nombre_BonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_BonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_BonoActionPerformed

    private void MontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarBono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarBono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarBono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarBono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarBono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JLabel Error_fecha;
    private javax.swing.JTextField Monto;
    private javax.swing.JTextField Nombre_Bono;
    private javax.swing.JButton Registrar;
    private javax.swing.JTextField anios_minimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
