/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz.bono;

import Interfaz.bono.*;
import ConectionDB.ConectionDB;
import Interfaz.BG_inicio;
import Interfaz.Menu;
import java.awt.*;
import java.awt.Component;
import java.awt.event.*;
import javax.swing.table.*;
import java.sql.*;
import popups.Popups;

/**
 *
 * @author RouryR
 */
public class VistaBono extends javax.swing.JPanel {

    Popups popups = new Popups();
    private AgregarBono agregarBono;

    /**
     * Creates new form VistaUsuarios2
     */
    public VistaBono() {
        initComponents();
        cargarDatos();
        Ajustar_Tamano_Columnas(TableBono);

    }

     public void cargarDatos() {
        DefaultTableModel model = (DefaultTableModel) TableBono.getModel();
        model.setRowCount(0);
        ConectionDB conexionDB = new ConectionDB();
        try (Connection conn = conexionDB.getConnection(); CallableStatement stmt = conn.prepareCall("{call Bonos.PROCEDURE_VISTA_Bonos(?)}")) {         
            stmt.registerOutParameter(1, java.sql.Types.REF_CURSOR);

            stmt.execute();

            try (ResultSet rs = (ResultSet) stmt.getObject(1)) {
                while (rs.next()) {
                    Object[] fila = new Object[4];
                    fila[0] = rs.getInt("ID_Bono");
                    fila[1] = rs.getString("sNombre_beneficio");
                    fila[2] = rs.getInt("nBono");
                    fila[3] = rs.getInt("Anos_Minimos");
                    model.addRow(fila);
                }
                for (int i = 0; i < TableBono.getColumnCount(); i++) {
                    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                    centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
                    TableBono.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Ajustar_Tamano_Columnas(javax.swing.JTable tabla) {
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            TableColumn column = tabla.getColumnModel().getColumn(i);
            int Ancho_Max = 0;
            for (int row = 0; row < tabla.getRowCount(); row++) {
                TableCellRenderer celdaRenderer = tabla.getCellRenderer(row, i);
                Object value = tabla.getValueAt(row, i);
                Component celda = celdaRenderer.getTableCellRendererComponent(tabla, value, false, false, row, i);
                Ancho_Max = Math.max(Ancho_Max, celda.getPreferredSize().width);
            }
            column.setPreferredWidth(Ancho_Max);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopup = new javax.swing.JPopupMenu();
        Editar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBono = new javax.swing.JTable();
        Regresar = new javax.swing.JButton();
        Agregar_Bono = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Editar.setBackground(new java.awt.Color(255, 255, 255));
        Editar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Editar.setForeground(new java.awt.Color(0, 102, 204));
        Editar.setText("Editar");
        Editar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153), null, null));
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPopup.add(Editar);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Bonos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 2, 36), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        TableBono.setAutoCreateRowSorter(true);
        TableBono.setBackground(new java.awt.Color(102, 102, 102));
        TableBono.setForeground(new java.awt.Color(255, 255, 255));
        TableBono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Monto", "Antiguedad necesaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableBono.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableBono.setColumnSelectionAllowed(true);
        TableBono.setComponentPopupMenu(jPopup);
        TableBono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableBono.setSelectionBackground(new java.awt.Color(153, 204, 0));
        TableBono.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TableBono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBonoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBono);
        TableBono.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        Regresar.setBackground(new java.awt.Color(204, 204, 204));
        Regresar.setForeground(new java.awt.Color(0, 0, 0));
        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        Regresar.setText("REGRESAR");
        Regresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), null, null));
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        Agregar_Bono.setBackground(new java.awt.Color(162, 171, 205));
        Agregar_Bono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Agregar_Bono.setForeground(new java.awt.Color(0, 0, 0));
        Agregar_Bono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        Agregar_Bono.setText("Agregar Bono");
        Agregar_Bono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 153, 0), null, null));
        Agregar_Bono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar_Bono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_BonoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Administración de Bonos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Agregar_Bono)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(370, Short.MAX_VALUE)
                    .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(369, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Agregar_Bono, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(459, Short.MAX_VALUE)
                    .addComponent(Regresar)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
 
    
    private void TableBonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBonoMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int x = evt.getX();
            int y = evt.getY();

            int row = TableBono.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                TableBono.setRowSelectionInterval(row, row);
            }
            jPopup.show(evt.getComponent(), x, y);
        }
    }//GEN-LAST:event_TableBonoMouseClicked

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.setVisible(false);
        BG_inicio pagina = new BG_inicio();
        pagina.setSize(916, 558);
        pagina.setLocation(0, 0);
        Menu.Contenido.removeAll();
        Menu.Contenido.add(pagina, BorderLayout.CENTER);
        Menu.Contenido.revalidate();
        Menu.Contenido.repaint();
    }//GEN-LAST:event_RegresarActionPerformed

    private void Agregar_BonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_BonoActionPerformed
        agregarBono.Crud_ = "Creación";
        agregarBono.textoBoton_ = "Crear";
        agregarBono.isEdit_ = false;
        agregarBono = new AgregarBono();
        agregarBono.setVisible(true);
        agregarBono.setVistaBono(this);
    }//GEN-LAST:event_Agregar_BonoActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        int filaSeleccionada = TableBono.getSelectedRow();

        if (filaSeleccionada != -1) {
            int idBono = (int) TableBono.getValueAt(filaSeleccionada, 0);
            String nombre_Bono = (String) TableBono.getValueAt(filaSeleccionada, 1);
            String monto = String.valueOf( TableBono.getValueAt(filaSeleccionada, 2));
            String anios_necesarios = String.valueOf( TableBono.getValueAt(filaSeleccionada, 3));

            agregarBono.Crud_ = "Edición";
            agregarBono.textoBoton_ = "Actualizar";
            agregarBono.isEdit_ = true;
            agregarBono.ID_aEditar_ = idBono;
            agregarBono = new AgregarBono();
            agregarBono.setVistaBono(this);
            agregarBono.setDatosEdicion(nombre_Bono, monto, anios_necesarios);
            agregarBono.setVisible(true);
        } else {
            popups.error("Por favor, seleccione un registro para editar.");
        }
    }//GEN-LAST:event_EditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Bono;
    private javax.swing.JMenuItem Editar;
    private javax.swing.JButton Regresar;
    private javax.swing.JTable TableBono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopup;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
