/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Usuarios;

import ConectionDB.ConectionDB;
import java.awt.Color;
import java.awt.Component;
import popups.Popups;
import java.sql.*;
import java.util.Date;
import javax.swing.JComponent;
import javax.swing.UIManager;

/**
 * @author ROURY
 */
public class AgregarUsuarios extends javax.swing.JFrame {

    public static String Crud_;
    public static boolean isEdit_;
    public static String textoBoton_;
    public static int ID_aEditar_;
    private VistaUsuarios vistaUsuarios2;

    Popups popups = new Popups();

    public AgregarUsuarios() {
        initComponents();

        for (Component c : jDateChooser.getComponents()) {
            ((JComponent) c).setBackground(Color.white);
        }
    }

    //esto es un set no quitar el la palabra set antes del nombre del metodo
    public void setVistaUsuarios2(VistaUsuarios vistaUsuarios2) {
        this.vistaUsuarios2 = vistaUsuarios2;
    }

    public void actualizarTabla() {
        if (vistaUsuarios2 != null) {
            vistaUsuarios2.cargarDatos();
        }
    }

    public void limpiarCampos() {
        Nombre.setText("");
        Apellido1.setText("");
        Apellido2.setText("");
        Cedula.setText("");
        Salario.setText("");
        Telefono.setText("");
        Provincia.setText("");
        Canton.setText("");
        Distrito.setText("");
        Bono.setText("");
        Rol.setSelectedIndex(0);
    }

    public void setDatosEdicion(String nombre, String telefono, String apellido1, String apellido2, String cedula,
            int salario, String provincia, String canton, String distrito, String rol, String bono, Date contratacion) {
        Nombre.setText(nombre);
        Apellido1.setText(apellido1);
        Apellido2.setText(apellido2);
        Cedula.setText(cedula);
        Salario.setText(String.valueOf(salario));
        Telefono.setText(telefono);
        Provincia.setText(provincia);
        Canton.setText(canton);
        Distrito.setText(distrito);
        Rol.setSelectedItem(rol);
        Bono.setText(bono);
        jDateChooser.setDate(contratacion);
        jDateChooser.setEnabled(false);
            jDateChooser.getDateEditor().getUiComponent().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cerrar = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        warning = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Nombre = new javax.swing.JTextField();
        Apellido1 = new javax.swing.JTextField();
        Apellido2 = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Provincia = new javax.swing.JTextField();
        Distrito = new javax.swing.JTextField();
        Canton = new javax.swing.JTextField();
        Salario = new javax.swing.JTextField();
        Bono = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Rol = new javax.swing.JComboBox<>();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        Error_fecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), Crud_ + " de Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Cerrar.setBackground(new java.awt.Color(153, 0, 0));
        Cerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setText("Cerrar");
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        Registrar.setBackground(new java.awt.Color(0, 102, 255));
        Registrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setText(textoBoton_);
        Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        warning.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("* Campos Obligatorios");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Por favor llene toda la información necesaria");

        jPanel2.setBackground(new java.awt.Color(162, 171, 205));

        Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Nombre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Apellido1.setBackground(new java.awt.Color(255, 255, 255));
        Apellido1.setForeground(new java.awt.Color(0, 0, 0));
        Apellido1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Apellido 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        Apellido2.setBackground(new java.awt.Color(255, 255, 255));
        Apellido2.setForeground(new java.awt.Color(0, 0, 0));
        Apellido2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Apellido 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        Apellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Apellido2KeyTyped(evt);
            }
        });

        Cedula.setBackground(new java.awt.Color(255, 255, 255));
        Cedula.setForeground(new java.awt.Color(0, 0, 0));
        Cedula.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Cédula", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaKeyTyped(evt);
            }
        });

        Telefono.setBackground(new java.awt.Color(255, 255, 255));
        Telefono.setForeground(new java.awt.Color(0, 0, 0));
        Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Teléfono", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(162, 171, 205));

        Provincia.setBackground(new java.awt.Color(255, 255, 255));
        Provincia.setForeground(new java.awt.Color(0, 0, 0));
        Provincia.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Provincia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        Distrito.setBackground(new java.awt.Color(255, 255, 255));
        Distrito.setForeground(new java.awt.Color(0, 0, 0));
        Distrito.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "*Distrito", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        Canton.setBackground(new java.awt.Color(255, 255, 255));
        Canton.setForeground(new java.awt.Color(0, 0, 0));
        Canton.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Canton", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        Salario.setBackground(new java.awt.Color(255, 255, 255));
        Salario.setForeground(new java.awt.Color(0, 0, 0));
        Salario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Salario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        Salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioActionPerformed(evt);
            }
        });
        Salario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SalarioKeyTyped(evt);
            }
        });

        Bono.setEditable(false);
        Bono.setBackground(new java.awt.Color(255, 255, 255));
        Bono.setForeground(new java.awt.Color(0, 0, 0));
        Bono.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Bono", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        Bono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BonoActionPerformed(evt);
            }
        });
        Bono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Distrito, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Canton, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bono, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Distrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Canton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        Rol.setBackground(new java.awt.Color(255, 255, 255));
        Rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Chofer", "Gerente", "Mantenimiento" }));
        Rol.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "* Tipo de Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        Rol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolActionPerformed(evt);
            }
        });

        jDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Fecha de Contratación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Rol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Error_fecha.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Error_fecha.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(warning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Error_fecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Error_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar)
                    .addComponent(Registrar))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CerrarActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        if (isEdit_) {
            String nombre = Nombre.getText();
            String cedula = Cedula.getText();
            String rol = Rol.getSelectedItem().toString();
            String apellido1 = Apellido1.getText();
            String apellido2 = Apellido2.getText();
            String salario = Salario.getText();
            String provincia = Provincia.getText();
            String canton = Canton.getText();
            String distrito = Distrito.getText();
            String telefono = Telefono.getText();
            

            if (jDateChooser.getDate() == null) {
                Error_fecha.setText("ATENCIÓN: Por favor, seleccione la fecha de contratación.");
                return;
            }

            java.sql.Date fechaSeleccionada = new java.sql.Date(jDateChooser.getDate().getTime());

            Color colorError = new Color(255, 204, 204);

            if (fechaSeleccionada == null || nombre.isEmpty() || apellido1.isEmpty() || apellido2.isEmpty()
                    || cedula.isEmpty() || telefono.isEmpty() || salario.isEmpty() || provincia.isEmpty()
                    || canton.isEmpty() || distrito.isEmpty() || rol.equals("-")) {

                if (nombre.isEmpty()) {
                    Nombre.setBackground(colorError);
                } else {
                    Nombre.setBackground(Color.WHITE);
                }

                if (apellido1.isEmpty()) {
                    Apellido1.setBackground(colorError);
                } else {
                    Apellido1.setBackground(Color.WHITE);
                }

                if (apellido2.isEmpty()) {
                    Apellido2.setBackground(colorError);
                } else {
                    Apellido2.setBackground(Color.WHITE);
                }

                if (cedula.isEmpty()) {
                    Cedula.setBackground(colorError);
                } else {
                    Cedula.setBackground(Color.WHITE);
                }

                if (salario.isEmpty()) {
                    Salario.setBackground(colorError);
                } else {
                    Salario.setBackground(Color.WHITE);
                }

                if (provincia.isEmpty()) {
                    Provincia.setBackground(colorError);
                } else {
                    Provincia.setBackground(Color.WHITE);
                }

                if (canton.isEmpty()) {
                    Canton.setBackground(colorError);
                } else {
                    Canton.setBackground(Color.WHITE);
                }

                if (distrito.isEmpty()) {
                    Distrito.setBackground(colorError);
                } else {
                    Distrito.setBackground(Color.WHITE);
                }

                if (telefono.isEmpty()) {
                    Telefono.setBackground(colorError);
                } else {
                    Telefono.setBackground(Color.WHITE);
                }

                if (fechaSeleccionada == null) {
                    Error_fecha.setText("ATENCIÓN: Por favor, seleccione la fecha de contratación.");
                } else {
                    jDateChooser.getCalendarButton().setBackground(UIManager.getColor("Button.background"));
                }

                if (rol.equals("-")) {
                    Rol.setBackground(colorError);
                } else {
                    Rol.setBackground(Color.WHITE);
                }

                warning.setText("ATENCIÓN: Por favor, complete todos los campos.");
                return;
            }

            Connection conn = null;
            CallableStatement stmt = null;

            try {
                ConectionDB conexionDB = new ConectionDB();
                conn = conexionDB.getConnection();

                String sql = "{CALL Procedure_EditarPersona(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}";
                stmt = conn.prepareCall(sql);
                stmt.setInt(1, ID_aEditar_);
                stmt.setString(2, nombre);
                stmt.setString(3, apellido1);
                stmt.setString(4, apellido2);
                stmt.setString(5, cedula);
                stmt.setInt(6, Integer.parseInt(salario));
                stmt.setString(7, provincia);
                stmt.setString(8, canton);
                stmt.setString(9, distrito);
                stmt.setString(10, rol);
                stmt.setString(11, telefono);

                stmt.executeUpdate();
                popups.pulgar_arriba("Usuario Editado exitosamente.");
                actualizarTabla();
                this.setVisible(false);
            } catch (SQLException e) {
                e.printStackTrace();
                popups.error("Error al Editada la Usuario.");
            } finally {
                try {
                    if (stmt != null) {
                        stmt.close();
                    }
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        } else {
            String nombre = Nombre.getText();
            String cedula = Cedula.getText();
            String rol = Rol.getSelectedItem().toString();
            String apellido1 = Apellido1.getText();
            String apellido2 = Apellido2.getText();
            String salario = Salario.getText();
            String provincia = Provincia.getText();
            String canton = Canton.getText();
            String distrito = Distrito.getText();
            String telefono = Telefono.getText();

            if (jDateChooser.getDate() == null) {
                Error_fecha.setText("ATENCIÓN: Por favor, seleccione la fecha de contratación.");
                return;
            }

            java.sql.Date fechaSeleccionada = new java.sql.Date(jDateChooser.getDate().getTime());

            Color colorError = new Color(255, 204, 204);

            if (fechaSeleccionada == null || nombre.isEmpty() || apellido1.isEmpty() || apellido2.isEmpty()
                    || cedula.isEmpty() || telefono.isEmpty() || salario.isEmpty() || provincia.isEmpty()
                    || canton.isEmpty() || distrito.isEmpty() || rol.equals("-")) {

                if (nombre.isEmpty()) {
                    Nombre.setBackground(colorError);
                } else {
                    Nombre.setBackground(Color.WHITE);
                }

                if (apellido1.isEmpty()) {
                    Apellido1.setBackground(colorError);
                } else {
                    Apellido1.setBackground(Color.WHITE);
                }

                if (apellido2.isEmpty()) {
                    Apellido2.setBackground(colorError);
                } else {
                    Apellido2.setBackground(Color.WHITE);
                }

                if (cedula.isEmpty()) {
                    Cedula.setBackground(colorError);
                } else {
                    Cedula.setBackground(Color.WHITE);
                }

                if (salario.isEmpty()) {
                    Salario.setBackground(colorError);
                } else {
                    Salario.setBackground(Color.WHITE);
                }

                if (provincia.isEmpty()) {
                    Provincia.setBackground(colorError);
                } else {
                    Provincia.setBackground(Color.WHITE);
                }

                if (canton.isEmpty()) {
                    Canton.setBackground(colorError);
                } else {
                    Canton.setBackground(Color.WHITE);
                }

                if (distrito.isEmpty()) {
                    Distrito.setBackground(colorError);
                } else {
                    Distrito.setBackground(Color.WHITE);
                }

                if (telefono.isEmpty()) {
                    Telefono.setBackground(colorError);
                } else {
                    Telefono.setBackground(Color.WHITE);
                }

                if (fechaSeleccionada == null) {
                    Error_fecha.setText("ATENCIÓN: Por favor, seleccione la fecha de contratación.");
                } else {
                    jDateChooser.getCalendarButton().setBackground(UIManager.getColor("Button.background"));
                }

                if (rol.equals("-")) {
                    Rol.setBackground(colorError);
                } else {
                    Rol.setBackground(Color.WHITE);
                }

                warning.setText("ATENCIÓN: Por favor, complete todos los campos.");
                return;
            }

            Connection conn = null;
            CallableStatement stmt = null;

            try {
                ConectionDB conexionDB = new ConectionDB();
                conn = conexionDB.getConnection();

                String sql = "{CALL PROCEDURE_REGISTRARPERSONA(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}";
                stmt = conn.prepareCall(sql);

                stmt.setString(1, nombre);
                stmt.setString(2, apellido1);
                stmt.setString(3, apellido2);
                stmt.setString(4, cedula);
                stmt.setInt(5, Integer.parseInt(salario));
                stmt.setString(6, rol);
                stmt.setString(7, provincia);
                stmt.setString(8, canton);
                stmt.setString(9, distrito);
                stmt.setString(10, telefono);
                stmt.setDate(11, fechaSeleccionada);

                stmt.executeUpdate();
                popups.pulgar_arriba("Usuario registrada exitosamente.");
                actualizarTabla();
                limpiarCampos();
            } catch (SQLException e) {
                e.printStackTrace();
                popups.error("Error al registrar la Usuario.");
            } finally {
                try {
                    if (stmt != null) {
                        stmt.close();
                    }
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyTyped
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <= 57;
        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_CedulaKeyTyped

    private void RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolActionPerformed

    }//GEN-LAST:event_RolActionPerformed

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void SalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalarioActionPerformed

    private void SalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SalarioKeyTyped
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <= 57;
        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_SalarioKeyTyped

    private void Apellido2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Apellido2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido2KeyTyped

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <= 57;
        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoKeyTyped

    private void BonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BonoActionPerformed

    private void BonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_BonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido1;
    private javax.swing.JTextField Apellido2;
    private javax.swing.JTextField Bono;
    private javax.swing.JTextField Canton;
    private javax.swing.JTextField Cedula;
    private javax.swing.JButton Cerrar;
    private javax.swing.JTextField Distrito;
    private javax.swing.JLabel Error_fecha;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Provincia;
    private javax.swing.JButton Registrar;
    private javax.swing.JComboBox<String> Rol;
    private javax.swing.JTextField Salario;
    private javax.swing.JTextField Telefono;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
