/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz.Bus;

import ConectionDB.ConectionDB;
import Interfaz.Bus.*;
import Interfaz.BG_inicio;
import Interfaz.Menu;
import java.awt.*;
import java.awt.Component;
import java.awt.event.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.sql.*;
import popups.Popups;

/**
 *
 * @author RouryR
 */
public class VistaBus extends javax.swing.JPanel {

    Popups popups = new Popups();
    private AgregarBus agregarBus;

    public VistaBus() {
        initComponents();
        cargarDatos();
        Ajustar_Tamano_Columnas(TableBus);
    }

    public void cargarDatos() {
        DefaultTableModel model = (DefaultTableModel) TableBus.getModel();
        model.setRowCount(0);

        ConectionDB conexionDB = new ConectionDB();
        try (Connection conn = conexionDB.getConnection(); CallableStatement stmt = conn.prepareCall("{call Procedure_Vista_Buses(?)}")) {

            stmt.registerOutParameter(1, java.sql.Types.REF_CURSOR);

            stmt.execute();

            try (ResultSet rs = (ResultSet) stmt.getObject(1)) {
                while (rs.next()) {
                    Object[] fila = new Object[8];
                    fila[0] = rs.getInt("NPLACA");
                    fila[1] = rs.getString("SMODELO");
                    fila[2] = rs.getString("SMARCA");
                    fila[3] = rs.getInt("SANIO");
                    fila[4] = rs.getInt("SCAPACIDAD");
                    fila[5] = rs.getString("SESTADO");
                    fila[6] = rs.getString("sNombre_Completo");
                    fila[7] = rs.getString("SCEDULA");

                    model.addRow(fila);
                }

                for (int i = 0; i < TableBus.getColumnCount(); i++) {
                    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                    centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
                    TableBus.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Ajustar_Tamano_Columnas(javax.swing.JTable tabla) {
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            TableColumn column = tabla.getColumnModel().getColumn(i);
            int Ancho_Max = 0;
            for (int row = 0; row < tabla.getRowCount(); row++) {
                TableCellRenderer celdaRenderer = tabla.getCellRenderer(row, i);
                Object value = tabla.getValueAt(row, i);
                Component celda = celdaRenderer.getTableCellRendererComponent(tabla, value, false, false, row, i);
                Ancho_Max = Math.max(Ancho_Max, celda.getPreferredSize().width);
            }
            column.setPreferredWidth(Ancho_Max);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopup = new javax.swing.JPopupMenu();
        Editar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBus = new javax.swing.JTable();
        Regresar = new javax.swing.JButton();
        Agregar_bus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Editar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Editar.setForeground(new java.awt.Color(0, 102, 204));
        Editar.setText("Editar");
        Editar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153), null, null));
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPopup.add(Editar);

        Eliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(204, 0, 51));
        Eliminar.setText("Eliminar");
        Eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPopup.add(Eliminar);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Buses", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 2, 36), new java.awt.Color(51, 51, 51))); // NOI18N

        TableBus.setAutoCreateRowSorter(true);
        TableBus.setBackground(new java.awt.Color(102, 102, 102));
        TableBus.setForeground(new java.awt.Color(255, 255, 255));
        TableBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PLACA", "MODELO", "MARCA", "AÑO", "CAPACIDAD", "ESTADO", "CHOFER", "CEDULA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableBus.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableBus.setColumnSelectionAllowed(true);
        TableBus.setComponentPopupMenu(jPopup);
        TableBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableBus.setSelectionBackground(new java.awt.Color(153, 204, 0));
        TableBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBus);
        TableBus.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        TableBus.getAccessibleContext().setAccessibleName("");

        Regresar.setBackground(new java.awt.Color(255, 204, 153));
        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        Regresar.setText("REGRESAR");
        Regresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), null, null));
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        Agregar_bus.setBackground(new java.awt.Color(255, 204, 153));
        Agregar_bus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Agregar_bus.setForeground(new java.awt.Color(0, 0, 0));
        Agregar_bus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/autobus-escolar_2.png"))); // NOI18N
        Agregar_bus.setText("Agregar Bus");
        Agregar_bus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 153, 0), null, null));
        Agregar_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_busActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Administración de Buses");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Agregar_bus)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(370, Short.MAX_VALUE)
                    .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(369, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Agregar_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(459, Short.MAX_VALUE)
                    .addComponent(Regresar)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TableBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBusMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int x = evt.getX();
            int y = evt.getY();

            int row = TableBus.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                TableBus.setRowSelectionInterval(row, row);
            }
            jPopup.show(evt.getComponent(), x, y);
        }
    }//GEN-LAST:event_TableBusMouseClicked

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.setVisible(false);
        BG_inicio pagina = new BG_inicio();
        pagina.setSize(916, 558);
        pagina.setLocation(0, 0);
        Menu.Contenido.removeAll();
        Menu.Contenido.add(pagina, BorderLayout.CENTER);
        Menu.Contenido.revalidate();
        Menu.Contenido.repaint();
    }//GEN-LAST:event_RegresarActionPerformed

    private void Agregar_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_busActionPerformed
        agregarBus.Crud_ = "Creación";
        agregarBus.textoBoton_ = "Crear";
        agregarBus.isEdit_ = false;
        agregarBus = new AgregarBus();
        agregarBus.setVisible(true);
    }//GEN-LAST:event_Agregar_busActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        int filaSeleccionada = TableBus.getSelectedRow();
        if (filaSeleccionada != -1) {
            int placa = (int) TableBus.getValueAt(filaSeleccionada, 0);
            String modelo = String.valueOf(TableBus.getValueAt(filaSeleccionada, 1));
            String marca = String.valueOf(TableBus.getValueAt(filaSeleccionada, 2));
            String anio = String.valueOf(TableBus.getValueAt(filaSeleccionada, 3));
            String capacidad = String.valueOf(TableBus.getValueAt(filaSeleccionada, 4));
            String estado = String.valueOf(TableBus.getValueAt(filaSeleccionada, 5));
            String chofer = (String) TableBus.getValueAt(filaSeleccionada, 6);  //

            agregarBus.Crud_ = "Edición";
            agregarBus.textoBoton_ = "Actualizar";
            agregarBus.isEdit_ = true;
            agregarBus.ID_aEditar_ = placa;
            agregarBus = new AgregarBus();
            agregarBus.setVistaBus(this);
            agregarBus.setDatosEdicion(placa, modelo, marca, anio, capacidad, estado, chofer);
            agregarBus.setVisible(true);
        } else {
            popups.error("Por favor, seleccione un registro para editar.");
        }

    }//GEN-LAST:event_EditarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int filaSeleccionada = TableBus.getSelectedRow();

        if (filaSeleccionada != -1) {
            int placa = (int) TableBus.getValueAt(filaSeleccionada, 0);

            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este bus?",
                    "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                Connection conn = null;
                CallableStatement stmt = null;

                try {
                    ConectionDB conexionDB = new ConectionDB();
                    conn = conexionDB.getConnection();

                    conn.setAutoCommit(false);

                    String sqlEliminarBus = "{call PROCEDURE_ELIMINARBUS(?)}";
                    stmt = conn.prepareCall(sqlEliminarBus);
                    stmt.setInt(1, placa);

                    stmt.executeUpdate();

                    conn.commit();
                    popups.pulgar_arriba("Registro eliminado correctamente.");
                    cargarDatos();

                } catch (SQLException e) {
                    try {
                        if (conn != null) {
                            conn.rollback();
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    e.printStackTrace();
                    popups.error("Error al eliminar el registro.");
                } finally {
                    try {
                        if (stmt != null) {
                            stmt.close();
                        }
                        if (conn != null) {
                            conn.close();
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
            }
        } else {
            popups.error("Por favor, seleccione un registro para eliminar.");
        }
    }//GEN-LAST:event_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_bus;
    private javax.swing.JMenuItem Editar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JButton Regresar;
    private javax.swing.JTable TableBus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopup;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
