/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz.Ayuda;

import Interfaz.Menu;
import Interfaz.BG_inicio;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author ROURY
 */
public class Ayuda extends javax.swing.JPanel {


    public Ayuda() {
        initComponents();

        About.setContentType("text/html");
        About.setText("<html>"
                + "<body style='font-family: Arial, sans-serif; font-size: 11px; text-align: center;'>"
                + "<h1 style='color: blue;'>Versión de la herramienta.</b> Avance 1 V 1.0.16</h1>"
                + "<p style='color: green;'><b>Cola:</b> Solución dada por Eduardo, Fiorella</p>"
                + "<p style='color: orange;'><b>Pilas:</b> Solución dada por Kenneth</p>"
                + "<p style='color: purple;'><b>NodoCola:</b> Solución dada por Eduardo</p>"
                + "<p style='color: brown;'><b>NodoPila:</b> Solución dada por Kenneth</p>"
                + "<p style='color: navy;'><b>Paciente:</b> Solución dada por Kenneth</p>"
                + "<p style='color: teal;'><b>Interfaz:</b> Solución dada por Diego</p>"
                + "<p style='color: magenta;'><b>Atender Paciente:</b> Solución dada por Diego</p>"
                + "<p style='color: cyan;'><b>Abandonar Cola:</b> Solución dada por Eduardo</p>"
                + "<p style='color: maroon;'><b>Gestionar llegada:</b> Solución dada por Fiorella</p>"
                + "<p style='color: darkgoldenrod;'><b>Pendientes:</b> Solución dada por Fiorella</p>"
                + "<p style='color: darkcyan;'><b>Seleccion Ficha:</b> Solución dada por Eduardo</p>"
                + "<p style='color: blue;'><b>Creación de Ficha:</b> Solución dada por Diego</p>"
                + "<p style='color: orange;'><b>Quejas:</b> Solución dada por Fiorella</p>"
                + "<h1 style='color: blue;'>Versión de la herramienta.</b> Avance 2 V 2.0.22</h1>"
                + "<p style='color: blue;'><b>Correccion de errores de la V1:</b> Solución dada por Diego</p>"
                + "<p style='color: teal;'><b>ListaSimple:</b> Solución dada por Eduardo</p>"
                + "<p style='color: purple;'><b>NodoListaSimple:</b> Solución dada por Eduardo</p>"
                + "<p style='color: green;'><b>ListasCircularesSimples:</b> Solución dada por Kenneth</p>"
                + "<p style='color: blue;'><b>NodoListasCircularesSimples:</b> Solución dada por Kenneth</p>"
                + "<p style='color: cyan;'><b>ListaCircularDoble:</b> Solución dada por Eduardo</p>"
                + "<p style='color: orange;'><b>NodoListaCircularDoble:</b> Solución dada por Eduardo</p>"
                + "<p style='color: maroon;'><b>Cambios en el Menu:</b> Solución dada por Eduardo</p>"
                + "<p style='color: green;'><b>Atender pacientes:</b> Solución dada por Diego</p>"
                + "<p style='color: teal;'><b>Consulta de bitacora:</b> Solución dada por Eduardo</p>"
                + "<p style='color: cyan;'><b>Consulta de expediente Unico:</b> Solución dada por Diego</p>"
                + "<h1 style='color: blue;'>Versión de la herramienta.</b> Avance 3 V 3.0.30</h1>"
                + "<p style='color: maroon;'><b>Correccion de errores de la V2:</b> Solución dada por Eduardo</p>"
                + "<p style='color: cyan;'><b>Creacion de ventana chatbot:</b> Solución dada por Eduardo</p>"
                + "<p style='color: green;'><b>Logica del arbol:</b> Solución dada por Kenneth</p>"
                + "<p style='color: teal;'><b>Mantenimiento del chatBot:</b> Solución dada por Diego</p>"
                + "<p style='color: blue;'><b>Listas de preguntas:</b> Solución dada por Diego</p>"
                + "</body>"
                + "</html>");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        About = new javax.swing.JTextPane();
        Regresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(186, 126, 185));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Avances del proyecto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 36))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        About.setEditable(false);
        jScrollPane2.setViewportView(About);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 50, 594, 390));

        Regresar.setBackground(new java.awt.Color(255, 153, 153));
        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        Regresar.setText("REGRESAR");
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 165, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.setVisible(false);
        BG_inicio pagina = new BG_inicio();
        pagina.setSize(650, 581);
        pagina.setLocation(0, 0);

        Menu.Contenido.removeAll();
        Menu.Contenido.add(pagina, BorderLayout.CENTER);
        Menu.Contenido.revalidate();
        Menu.Contenido.repaint();
    }//GEN-LAST:event_RegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane About;
    private javax.swing.JButton Regresar;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
