/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz.Revision;
import ConectionDB.ConectionDB;
import Interfaz.BG_inicio;
import Interfaz.Menu;
import java.awt.*;
import java.awt.Component;
import java.awt.event.*;
import javax.swing.table.*;
import java.sql.*;
import popups.Popups;


/**
 *
 * @author RouryR
 */
public class VistaRevision extends javax.swing.JPanel {

    Popups popups = new Popups();
    private AgregarRevision agregarRevision;

    public VistaRevision() {
        initComponents();
        cargarDatos();
        Ajustar_Tamano_Columnas(TableRevision);

    }

    public void cargarDatos() {
        DefaultTableModel model = (DefaultTableModel) TableRevision.getModel();
        model.setRowCount(0);
        ConectionDB conexionDB = new ConectionDB();

        try (Connection conn = conexionDB.getConnection(); CallableStatement stmt = conn.prepareCall("{call Procedure_lista_revision(?)}")) {

            stmt.registerOutParameter(1, oracle.jdbc.OracleTypes.CURSOR);

            stmt.execute();
            try (ResultSet rs = (ResultSet) stmt.getObject(1)) {
                while (rs.next()) {
                    Object[] fila = new Object[9];
                    fila[0] = rs.getInt("ID_Revision");
                    fila[1] = rs.getInt("Placa_Bus");
                    fila[2] = rs.getString("Modelo_Bus");
                    fila[3] = rs.getString("Marca_Bus");
                    fila[4] = rs.getDate("dFecha_Inicio");
                    fila[5] = rs.getDate("dFecha_Fin");
                    fila[6] = rs.getString("sDuracion");
                    fila[7] = rs.getString("Nombre_Mantenimiento");
                    fila[8] = rs.getString("Estado_Bus");
                    model.addRow(fila);
                }

                for (int i = 0; i < TableRevision.getColumnCount(); i++) {
                    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                    centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
                    TableRevision.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Ajustar_Tamano_Columnas(javax.swing.JTable tabla) {
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            TableColumn column = tabla.getColumnModel().getColumn(i);
            int Ancho_Max = 0;
            for (int row = 0; row < tabla.getRowCount(); row++) {
                TableCellRenderer celdaRenderer = tabla.getCellRenderer(row, i);
                Object value = tabla.getValueAt(row, i);
                Component celda = celdaRenderer.getTableCellRendererComponent(tabla, value, false, false, row, i);
                Ancho_Max = Math.max(Ancho_Max, celda.getPreferredSize().width);
            }
            column.setPreferredWidth(Ancho_Max);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopup = new javax.swing.JPopupMenu();
        Editar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRevision = new javax.swing.JTable();
        Regresar = new javax.swing.JButton();
        Agregar_Revision = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Editar.setBackground(new java.awt.Color(255, 255, 255));
        Editar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Editar.setForeground(new java.awt.Color(0, 102, 204));
        Editar.setText("Editar");
        Editar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153), null, null));
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPopup.add(Editar);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Revisión", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 2, 36), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        TableRevision.setAutoCreateRowSorter(true);
        TableRevision.setBackground(new java.awt.Color(102, 102, 102));
        TableRevision.setForeground(new java.awt.Color(255, 255, 255));
        TableRevision.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "PLACA", "MODELO", "MARCA", "FECHA INICIO", "FECHA FIN", "DURACIÓN", "MECÁNICO", "ESTADO BUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableRevision.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableRevision.setColumnSelectionAllowed(true);
        TableRevision.setComponentPopupMenu(jPopup);
        TableRevision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableRevision.setSelectionBackground(new java.awt.Color(153, 204, 0));
        TableRevision.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TableRevision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableRevisionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableRevision);
        TableRevision.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        Regresar.setBackground(new java.awt.Color(255, 102, 102));
        Regresar.setForeground(new java.awt.Color(0, 0, 0));
        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        Regresar.setText("REGRESAR");
        Regresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), null, null));
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        Agregar_Revision.setBackground(new java.awt.Color(255, 102, 102));
        Agregar_Revision.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Agregar_Revision.setForeground(new java.awt.Color(0, 0, 0));
        Agregar_Revision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        Agregar_Revision.setText("Agregar Revisión");
        Agregar_Revision.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 153, 0), null, null));
        Agregar_Revision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar_Revision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_RevisionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Administración de Revisiónes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Agregar_Revision)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(370, Short.MAX_VALUE)
                    .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(369, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Agregar_Revision, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(459, Short.MAX_VALUE)
                    .addComponent(Regresar)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void TableRevisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableRevisionMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int x = evt.getX();
            int y = evt.getY();

            int row = TableRevision.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                TableRevision.setRowSelectionInterval(row, row);
            }
            jPopup.show(evt.getComponent(), x, y);
        }
    }//GEN-LAST:event_TableRevisionMouseClicked

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.setVisible(false);
        BG_inicio pagina = new BG_inicio();
        pagina.setSize(916, 558);
        pagina.setLocation(0, 0);
        Menu.Contenido.removeAll();
        Menu.Contenido.add(pagina, BorderLayout.CENTER);
        Menu.Contenido.revalidate();
        Menu.Contenido.repaint();
    }//GEN-LAST:event_RegresarActionPerformed

    private void Agregar_RevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_RevisionActionPerformed
        agregarRevision.Crud_ = "Creación";
        agregarRevision.textoBoton_ = "Crear";
        agregarRevision.isEdit_ = false;
        agregarRevision = new AgregarRevision();
        agregarRevision.setVisible(true);
        agregarRevision.setVistaMantenimiento(this);
    }//GEN-LAST:event_Agregar_RevisionActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        int filaSeleccionada = TableRevision.getSelectedRow();

        if (filaSeleccionada != -1) {
            Object placaObject = TableRevision.getValueAt(filaSeleccionada, 1);
            String placa = placaObject.toString();

            Date fecha_inicio = (Date) TableRevision.getValueAt(filaSeleccionada, 4);
            Date fecha_fin = (Date) TableRevision.getValueAt(filaSeleccionada, 5);
            String duracion = (String) TableRevision.getValueAt(filaSeleccionada, 6);
            String mecanico = (String) TableRevision.getValueAt(filaSeleccionada, 7);

            agregarRevision.Crud_ = "Edición";
            agregarRevision.textoBoton_ = "Completar";
            agregarRevision.isEdit_ = true;

            agregarRevision.ID_aEditar_ = placa;
            agregarRevision = new AgregarRevision();
            agregarRevision.setVistaMantenimiento(this);

            agregarRevision.setDatosEdicion(fecha_inicio, fecha_fin, duracion, mecanico, placa);
            agregarRevision.setVisible(true);
        } else {
            popups.error("Por favor, seleccione un registro para editar.");
        }
    }//GEN-LAST:event_EditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Revision;
    private javax.swing.JMenuItem Editar;
    private javax.swing.JButton Regresar;
    private javax.swing.JTable TableRevision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopup;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
